NAME = serialize
SRC = main.cpp class/cpp/Serialize.cpp
DEPS = class/hpp/Serialize.hpp class/hpp/Data.hpp
CC = c++ -Wall -Wextra -Werror -std=c++98

.PHONY: all clean fclean re

all: $(NAME)

$(NAME): Makefile $(DEPS) $(SRC)
	$(CC) $(SRC) -o $(NAME)

clean:
	rm -rf $(NAME)

fclean: clean

re: fclean all
